# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
defaults: &defaults
  working_directory: ~/project
  docker:
    - image: circleci/node:8.11.3
jobs:
  build:
    <<: *defaults
    steps:
      - checkout
      
      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run: yarn install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      # run tests!
      - run: yarn build
      - run: ls .
      - persist_to_workspace:
          root: ~/project
          paths: 
            - dist
            - scripts
    publish:
      <<: *defaults
      steps: 
        - attach_workspace:
            at: dist

        - run:
          name: "Authenticate with registry" 
          command: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > ~/project/.npmrc
        - run: 
          name: 'has ./scripts'
          command: ls .
          #-run: node ./scripts/release/publish-to-npm.js
workflows:
  version: 2
  build-publish_to_npm:
    jobs: 
      - build 
      - publish:
          filters:
            branches:
              only: master
          #  tags:
          #    only: /^v.*/
          requires:
            - build

