# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
defaults: &defaults
  working_directory: ~/project
  docker:
    - image: circleci/node:8.11.3
jobs:
  build:
    <<: *defaults
    steps:
      - checkout
      
      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
      - restore_cache:
          keys: 
            - git-cache-
      - run: yarn install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - save_cache:
          paths:
            - .git
          key: git-cache-{{ .Branch }}
          # run tests!
      - run: yarn build
      - run: ls .
      - persist_to_workspace:
          root: ~/project
          paths: 
            - dist
            - scripts
            - example
  build_demo:
    <<: *defaults
    steps: 
      - restore_cache:
          keys:
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
      - restore_cache:
          keys:
            # fallback to using the latest cache if no exact match is found
            - git-cache      
      - attach_workspace:
          at: ~/project
      - run:
          name: "build example files" 
          command: |
            cd ./example/demo1 
            yarn
            yarn build
            ls -alt
      - run :
          name: "copy build to root"  
          command: node ./scripts/release/pushToGhPage.js && ls -a .
      - run: git status 
      - run: cd ~/project 
      
  
  publish:
    <<: *defaults
    steps: 
      - attach_workspace:
          at: ~/project

      - run:
          name: "Authenticate with registry" 
          command: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > ~/project/.npmrc
      - run: 
          name: 'check it has attach ./scripts '
          command: ls -a .
          #-run: node ./scripts/release/publish-to-npm.js
  
workflows:
  version: 2
  build-publish_to_npm:
    jobs: 
      - build 
      - build_demo:
          filters:
            branches:
              only: master
          requires:
            - build
      - publish:
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
          requires:
            - build

